version: '3'

services:
  api:
    build:
      context: ../api/
    ports:
      - "80:3000"
    restart: always
    volumes:
      - ../api/:/var/www/api/
    links:
     - neo4j
  neo4j:
    image: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
